version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    versioning-strategy: increase
    open-pull-requests-limit: 100
    labels:
      - ':house: pr: internal'
      - 'javascript'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        update-types: ['major', 'minor', 'patch']

  - package-ecosystem: 'maven'
    directory: '/core-java'
    target-branch: 'main'
    open-pull-requests-limit: 100
    labels:
      - ':house: pr: internal'
      - 'java'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    open-pull-requests-limit: 100
    labels:
      - ':house: pr: internal'
      - 'github_actions'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'