version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    versioning-strategy: increase
    open-pull-requests-limit: 100
    labels:
      - ':house: pr: internal'
      - 'javascript'
    reviewers:
      - 'boyka-core'
    schedule:
      interval: 'monthly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'

  - package-ecosystem: 'maven'
    directory: '/core-java'
    target-branch: 'main'
    open-pull-requests-limit: 100
    labels:
      - ':house: pr: internal'
      - 'java'
    reviewers:
      - 'boyka-core'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'

  - package-ecosystem: 'maven'
    directory: '/sample-tests'
    target-branch: 'main'
    open-pull-requests-limit: 100
    labels:
      - ':house: pr: internal'
      - 'java'
    reviewers:
      - 'boyka-core'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    open-pull-requests-limit: 100
    labels:
      - ':house: pr: internal'
      - 'github_actions'
    reviewers:
      - 'boyka-core'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'