version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    versioning-strategy: increase
    schedule:
      interval: 'daily'

  - package-ecosystem: 'maven'
    directory: '/core-java'
    target-branch: 'develop'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'maven'
    directory: '/sample-tests'
    target-branch: 'develop'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
