version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    versioning-strategy: widen
    schedule:
      interval: 'weekly'
      day: 'saturday'

  - package-ecosystem: 'maven'
    directory: '/core-java'
    target-branch: 'develop'
    versioning-strategy: widen
    schedule:
      interval: 'weekly'
      day: 'saturday'

  - package-ecosystem: 'maven'
    directory: '/sample-tests'
    target-branch: 'develop'
    versioning-strategy: widen
    schedule:
      interval: 'weekly'
      day: 'saturday'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    versioning-strategy: increase-if-necessary
    schedule:
      interval: 'weekly'
      day: 'saturday'
