version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'maven'
    directory: '/core-java'
    schedule:
      interval: 'weekly'
