name: 🐛 Raise a bug
description: |
  This template is used to create a new bug report.
  Please provide as much information as possible.
title: '🐛 : '
body:
  - type: input
    id: description
    attributes:
      label: ❓ What is the bug?
      placeholder: Describe the bug you are reporting
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: 🔢 What version of the framework is this bug related to?
      options:
        - 1.0.0 (Default)
    validations:
      required: true

  - type: dropdown
    id: app-type
    attributes:
      label: 🖥️ What application type is this bug for?
      multiple: true
      options:
        - API
        - WEB
        - ANDROID
        - IOS
        - NOT APPLICABLE
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 📃 Steps to reproduce
      description: We highly suggest including a screenshots and a bug report log (GitHub Gist link).
      placeholder: Tell us the steps required to trigger your bug.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: ✅ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true
