blank_issues_enabled: false
contact_links:
  - name: Want to discuss anything else?
    url: https://github.com/BoykaFramework/boyka-framework/discussions/new
    about: Create a discussion about it.
  - name: You can also join our Discord server
    url: https://dub.sh/boyka-discord
    about: Join our Discord server.
