name: ✨ Update existing Feature request
description: |
  This template is used to create a new feature request.
  Please provide as much information as possible.
labels:
  - '✨ goal: improvement'
  - '🏷 status: label work required'
  - '🏁 status: ready for dev'
title: '✨ Update feature:'
type: Enhancement
body:
  - type: dropdown
    id: domain-type
    attributes:
      label: 🖥️ What framework domain type is this feature for?
      options:
        - API
        - Web
        - Android
        - iOS
        - Workflow
        - Documentations
        - Dependencies
        - Issues / PR templates
        - NOT APPLICABLE
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📗 Description of the feature improvement request?
      placeholder: What is the expected behavior of the proposed feature?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🚧 Scenario where this would be used?
      placeholder: |
        What is the scenario this would be used? Why is this important to your workflow?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 💁 Supporting information
      placeholder: |
        Having additional evidence, data, tweets, blog posts, research, ... anything is extremely helpful.
        This information provides context to the scenario that may otherwise be lost.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ⚠️ Please limit one request per issue.
