version: "3"
services:
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4443
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4444
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4

  selenium-hub:
    image: selenium/hub:4.1.4-20220427
    container_name: selenium-hub
    ports:
      - "4444:4444"
