#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
yarn build:site
mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -f core-java/pom.xml -Pcoverage-per-test -Dsuite-xml=test-suites/testng-local-husky.xml
