name: Common Create PR workflow

on:
  workflow_call:
    inputs:
      source-branch:
        type: string
        description: Source Branch
        required: true
      target-branch:
        type: string
        description: Target Branch
        required: true
      title:
        type: string
        description: PR Title
        required: true
      is-feature:
        type: boolean
        description: Is this PR from a feature branch
        default: false
    secrets:
      token:
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    name: Create pull request from ${{ inputs.source-branch }} to ${{ inputs.target-branch }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Detect changes between ${{ inputs.source-branch }} and ${{ inputs.target-branch }}
        id: branch-changes
        uses: fjenik/detect-changes-between-two-branches@0.0.3
        with:
          repo-token: ${{ secrets.token }}
          target-branch: ${{ inputs.target-branch }}
          source-branch: ${{ inputs.source-branch }}

      - name: Detect changes output
        run: echo "Output of detect changes ${{ steps.branch-changes.outputs.is-source-branch-ahead }}"

      - name: Check if pr already exists
        id: pr-exists
        if: ${{ steps.branch-changes.outputs.is-source-branch-ahead == 'true' }}
        uses: fjenik/check-if-pr-exists@0.0.3
        with:
          repo-token: ${{ secrets.token }}
          target-branch: ${{ inputs.target-branch }}
          source-branch: ${{ inputs.source-branch }}

      - name: Print output
        run: echo "Output of pull request already exists ${{ steps.pr-exists.outputs.is-pr-already-created }}"

      - name: Create pull request
        if: ${{ steps.pr-exists.outputs.is-pr-already-created == 'false' && ! inputs.is-feature }}
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.token }}
          source_branch: ${{ inputs.source-branch }}
          destination_branch: ${{ inputs.target-branch }}
          pr_reviewer: boyka-core
          pr_title: ${{ inputs.title }}
          pr_draft: true
          pr_body: |
            _This PR was generated via github actions workflow_

            **Don't squash merge this PR**

      - name: Create feature pull request
        if: ${{ steps.pr-exists.outputs.is-pr-already-created == 'false' && inputs.is-feature }}
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.token }}
          source_branch: ${{ inputs.source-branch }}
          destination_branch: ${{ inputs.target-branch }}
          pr_reviewer: boyka-core
          pr_title: ${{ inputs.title }}
          pr_template: '.github/pull_request_template.md'
          pr_draft: true
