name: Create pull request develop branch from feature branch

on:
  push:
    branches:
      - issue-*

jobs:
  create-feature-to-develop-pr:
    uses: ./.github/workflows/common/_create-pr.yml
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}
    with:
      source-branch: ${{ github.ref_name }}
      target-branch: develop
      title: ${{ github.event.head_commit.message }}
      is-feature: true
