name: Create pull request develop branch from feature branch

on:
  push:
    branches:
      - issue-*

jobs:
  create-feature-to-develop-pr:
    uses: ./.github/workflows/_create-pr.yml
    with:
      source-branch: ${{ github.ref_name }}
      target-branch: develop
      title: ${{ github.event.head_commit.message }}
      is-feature: true
    secrets:
      GITHUB_AUTH: ${{ secrets.GITHUB_AUTH }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
