name: Create pull request develop branch from feature branch

on:
  push:
    branches:
      - issue-*

permissions:
  pull-requests: write

jobs:
  create-feature-to-develop-pr:
    uses: ./.github/workflows/_create-pr.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      source-branch: ${{ github.ref_name }}
      target-branch: develop
      title: ${{ github.event.head_commit.message }}
      is-feature: true
