name: Create pull request from develop to staging

on:
  push:
    branches:
      - develop

jobs:
  create-develop-to-staging-pr:
    uses: ./.github/workflows/common/_create-pr.yml
    with:
      source-branch: develop
      target-branch: staging
      title: 'chore(Internal): :bookmark: new release candidate'
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}
