name: Deploy boyka website on GitHub

on:
  pull_request:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/**'

concurrency:
  group: boyka-deploy-site-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  checks:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build site
        run: pnpm build:site

  gh-release:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build site
        run: pnpm build:site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
