name: Deploy boyka website on GitHub

on:
  pull_request:
    branches:
      - develop
      - staging
      - main
    paths:
      - 'website/**'
      - '.github/**'
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/**'

concurrency:
  group: boyka-deploy-site-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  checks:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build site
        run: yarn build:site

  gh-release:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build site
        run: yarn build:site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
