name: Label Feature and Bug PRs

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
