name: Deploy Pre-release to Maven Central

on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging
    types:
      - closed
    paths:
      - 'core-java/**'

env:
  GITHUB_AUTH: ${{ secrets.PUSH_TOKEN }}
  PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  prepare-pre-release:
    runs-on: ubuntu-latest

    outputs:
      new-version: ${{ steps.version.outputs.version }}
      old-version: ${{ steps.old_version.outputs.previous_version }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Get the previous release version
        id: old_version
        run: |
          export MVN_OLD_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "previous_version=${MVN_OLD_VERSION:1}" >> $GITHUB_OUTPUT

      - name: Update pre-release version
        run: yarn prerelease

      - name: Get the new pre-release version
        id: version
        run: |
          export MVN_VERSION=$(node -pe "require('./website/package.json').version")
          echo "version=$MVN_VERSION" >> $GITHUB_OUTPUT

      - name: Generate Change log
        if: steps.version.outputs.version != null
        run: |
          yarn changelog --from v${{ steps.old_version.outputs.previous_version }} --next-version v${{ steps.version.outputs.version }} > CHANGELOG.md

      - name: Upload updated version related files to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: version-files
          path: |
            ${{ github.workspace }}/CHANGELOG.md
            ${{ github.workspace }}/lerna.json
            ${{ github.workspace }}/website/package.json

  pre-release-snapshot:
    runs-on: ubuntu-latest
    needs: prepare-pre-release
    if: needs.prepare-pre-release.outputs.new-version != null
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Maven command to update snapshot version
        run: mvn build-helper:parse-version versions:set -f core-java/pom.xml -DnewVersion=${{ needs.prepare-pre-release.outputs.new-version }}-SNAPSHOT versions:commit

      - name: Release snapshot to Maven central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          nexus_username: ${{ env.NEXUS_USERNAME }}
          nexus_password: ${{ env.NEXUS_PASSWORD }}
          maven_profiles: release
          server_id: ossrh
          maven_args: --settings ${{ github.workspace }}/core-java/setting/settings.xml -f core-java/pom.xml -DskipTests -Dcheckstyle.skip -B

  pre-release:
    runs-on: ubuntu-latest
    needs:
      - prepare-pre-release
      - pre-release-snapshot

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Maven command to update pre-release version
        run: mvn build-helper:parse-version versions:set -f core-java/pom.xml -DnewVersion=${{ needs.prepare-pre-release.outputs.new-version }} versions:commit

      - name: Release to Maven central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          nexus_username: ${{ env.NEXUS_USERNAME }}
          nexus_password: ${{ env.NEXUS_PASSWORD }}
          maven_profiles: release
          server_id: ossrh
          maven_args: --settings ${{ github.workspace }}/core-java/setting/settings.xml -f core-java/pom.xml -DskipTests -Dcheckstyle.skip -B

      - name: Build the project JAR files
        run: mvn clean install -f core-java/pom.xml -DskipTests -Dcheckstyle.skip

      - name: Upload target folder
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            ${{ github.workspace }}/core-java/target

      - name: Upload version files folder
        uses: actions/upload-artifact@v3
        with:
          name: version-files
          path: |
            ${{ github.workspace }}/core-java/pom.xml

  push-pom:
    runs-on: ubuntu-latest
    needs:
      - prepare-pre-release
      - pre-release

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ env.PUSH_TOKEN }}

      - name: Download Version files
        uses: actions/download-artifact@v3
        with:
          name: version-files

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push updated version files
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            core-java/pom.xml
            lerna.json
            CHANGELOG.md
            website/package.json
          message: |
            chore(Internal): :bookmark: released v${{ needs.prepare-pre-release.outputs.old-version }} to maven central
          push: true
          default_author: user_info
          commit: --no-verify

  github-pre-release:
    runs-on: ubuntu-latest
    needs:
      - prepare-pre-release
      - push-pom

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download target folder
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Download Version files
        uses: actions/download-artifact@v3
        with:
          name: version-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ env.PUSH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: v${{ needs.prepare-pre-release.outputs.new-version }}
          name: Release Candidate Version ${{ needs.prepare-pre-release.outputs.new-version }}
          prerelease: true
          draft: false
          body_path: CHANGELOG.md
          discussion_category_name: Announcements
          generate_release_notes: false
          files: |
            core-java/target/*.jar
            core-java/target/*.pom
