name: Deploy Pre-release to Maven Central

on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging
    types:
      - closed
    paths:
      - 'core-java/**'

jobs:
  pre-release:
    uses: ./.github/workflows/_release.yml
    secrets:
      GITHUB_AUTH: ${{ secrets.GITHUB_AUTH }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
