name: Deploy Pre-release to Maven Central

on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging
    types:
      - closed
    paths:
      - 'core-java/**'

jobs:
  pre-release:
    uses: ./.github/workflows/_release.yml
    secrets:
      pushToken: ${{ secrets.PUSH_TOKEN }}
      gpgKey: ${{ secrets.GPG_PRIVATE_KEY }}
      gpgPass: ${{ secrets.GPG_PASSPHRASE }}
      nexusUser: ${{ secrets.NEXUS_USERNAME }}
      nexusPass: ${{ secrets.NEXUS_PASSWORD }}
