name: Deploy Release to GitHub and Maven Central

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Release Type'
        required: true
        options:
          - major
          - minor
          - patch
        default: 'minor'

env:
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
  TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    outputs:
      new-version: ${{ steps.version.outputs.version }}
      changelog: ${{ steps.changelog.outputs.changelog }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Get the previous release version
        id: old_version
        run: |
          export MVN_OLD_VERSION=$(node -pe "require('./package.json').version")
          echo "::set-output name=previous_version::$MVN_OLD_VERSION"

      - name: Update version major
        if: ${{ github.event.inputs.release_type == 'major' }}
        run: yarn run major

      - name: Update version minor
        if: ${{ github.event.inputs.release_type == 'minor' }}
        run: yarn run minor

      - name: Update version patch
        if: ${{ github.event.inputs.release_type == 'patch' }}
        run: yarn run patch

      - name: Get the new version
        id: version
        run: |
          export MVN_VERSION=$(node -pe "require('./website/package.json').version")
          echo "::set-output name=version::$MVN_VERSION"

      - name: Update the new version to main package.json
        run: yarn version ${{ steps.version.outputs.version }}

      - name: Create GitHub Release changelog
        id: changelog
        run: |
          export CHANGELOG=$(yarn changelog --from ${{ steps.old_version.outputs.previous_version }} --next-version ${{ steps.version.outputs.version }})
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Upload updated package.json to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            ${{ github.workspace }}/.yarn
            ${{ github.workspace }}/package.json
            ${{ github.workspace }}/website/package.json

  release-snapshot:
    runs-on: ubuntu-latest
    needs: prepare-release

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Download artifacts data
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Maven command to update snapshot version
        run: mvn build-helper:parse-version versions:set -f core-java/pom.xml -DnewVersion=${{ needs.prepare-release.outputs.new-version }}-SNAPSHOT versions:commit

      - name: Build the artifacts
        run: mvn clean install -f core-java/pom.xml -DskipTests -Dcheckstyle.skip

      - name: Release snapshot to Maven central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          nexus_username: ${{ env.NEXUS_USERNAME }}
          nexus_password: ${{ env.NEXUS_PASSWORD }}
          maven_profiles: release
          server_id: ossrh
          maven_args: --settings ${{ github.workspace }}/core-java/setting/settings.xml -f core-java/pom.xml -DskipTests -Dcheckstyle.skip -B

      - name: Upload target folder
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            ${{ github.workspace }}/package.json
            ${{ github.workspace }}/website/package.json
            ${{ github.workspace }}/core-java/target
            ${{ github.workspace }}/core-java/pom.xml

  release:
    runs-on: ubuntu-latest
    needs:
      - prepare-release
      - release-snapshot

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Download artifacts data
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Maven command to update release version
        run: mvn build-helper:parse-version versions:set -f core-java/pom.xml -DnewVersion=${{ needs.prepare-release.outputs.new-version }} versions:commit

      - name: Build the artifacts
        run: mvn clean install -f core-java/pom.xml -DskipTests -Dcheckstyle.skip

      - name: Release to Maven central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          nexus_username: ${{ env.NEXUS_USERNAME }}
          nexus_password: ${{ env.NEXUS_PASSWORD }}
          maven_profiles: release
          server_id: ossrh
          maven_args: --settings ${{ github.workspace }}/core-java/setting/settings.xml -f core-java/pom.xml -DskipTests -Dcheckstyle.skip -B

      - name: Upload target folder
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            ${{ github.workspace }}/package.json
            ${{ github.workspace }}/website/package.json
            ${{ github.workspace }}/core-java/target
            ${{ github.workspace }}/core-java/pom.xml

  push-pom:
    runs-on: ubuntu-latest
    needs:
      - release

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Download target folder
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push updated pom.xml
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            core-java/pom.xml
            package.json
            website/package.json
          message: 'chore(Internal): 🎉 Released latest version to Maven central'
          push: true
          default_author: user_info
          commit: --no-verify

  push-tag:
    runs-on: ubuntu-latest
    needs:
      - prepare-release
      - push-pom

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Download target folder
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create and Push Tag
        uses: EndBug/add-and-commit@v9
        with:
          tag: v${{ needs.prepare-release.outputs.new-version }}
          message: 🎉 Released to Maven central
          default_author: user_info
          push: true

  github-release-tweet:
    runs-on: ubuntu-latest
    needs:
      - prepare-release
      - push-tag

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Download target folder
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        id: gh-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: v${{ needs.prepare-release.outputs.new-version }}
          name: Version ${{ needs.prepare-release.outputs.new-version }}
          prerelease: false
          draft: false
          body: ${{ needs.prepare-release.outputs.changelog }}
          discussion_category_name: Announcements
          generate_release_notes: false
          files: |
            core-java/target/*.jar
            core-java/target/*.pom

      - name: Send Release Tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: |
            🎊 ✨ Released v${{ needs.prepare-release.outputs.new-version }} for #BoykaFramework\n\nCheck it out at ${{ steps.gh-release.outputs.url }}
          consumer-key: ${{ env.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ env.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ env.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ env.TWITTER_ACCESS_TOKEN_SECRET }}
