name: Test boyka-framework release

on:
  push:
    branches:
      - issue-*
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build the project
        run: mvn install -f core-java/pom.xml -DskipTests

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: release-${{ runner.os }}-maven-${{ github.sha }}

  test:
    needs:
      - build
    runs-on: macos-latest
    env:
      BS_USER: ${{ secrets.BS_USER }}
      BS_KEY: ${{ secrets.BS_KEY }}
      LT_USER: ${{ secrets.LT_USER }}
      LT_KEY: ${{ secrets.LT_KEY }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Restore local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: release-${{ runner.os }}-maven-${{ github.sha }}

      - name: Get the version
        id: version
        run: |
          export MVN_VERSION=$(node -pe "require('./website/package.json').version")
          echo "::set-output name=version::$MVN_VERSION"

      - name: Start Selenium Grid
        run: java -jar core-java/libs/selenium-server-4.3.0.jar standalone > sample-tests/selenium-grid.log &

      - name: All Test execution
        run: mvn clean test -f sample-tests/pom.xml -Dboyka.version=${{ steps.version.outputs.version }}

      - name: Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ${{ github.workspace }}/sample-tests/target/surefire-reports/*.xml
          reporter: java-junit

      - name: Upload target folder
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: target
          path: |
            ${{ github.workspace }}/sample-tests/logs
            ${{ github.workspace }}/sample-tests/selenium-grid.log
            ${{ github.workspace }}/sample-tests/target
            ${{ github.workspace }}/sample-tests/reports
