name: Test boyka-framework release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  test:
    runs-on: macos-latest
    env:
      BS_USER: ${{ secrets.BS_USER }}
      BS_KEY: ${{ secrets.BS_KEY }}
      LT_USER: ${{ secrets.LT_USER }}
      LT_KEY: ${{ secrets.LT_KEY }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: mvn clean install -f core-java/pom.xml -DskipTests -Dcheckstyle.skip

      - name: Get the version
        id: version
        run: |
          export MVN_VERSION=$(node -pe "require('./website/package.json').version")
          echo "version=$MVN_VERSION" >> $GITHUB_OUTPUT

      - name: Start Selenium Grid
        run: java -jar core-java/libs/selenium-server-4.8.0.jar standalone > sample-tests/selenium-grid.log &

      - name: All Test execution
        run: mvn clean test -f sample-tests/pom.xml -Dboyka.version=${{ steps.version.outputs.version }}

      - name: Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ${{ github.workspace }}/sample-tests/target/surefire-reports/*.xml
          reporter: java-junit

      - name: Upload target folder
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: target
          path: |
            ${{ github.workspace }}/sample-tests/logs
            ${{ github.workspace }}/sample-tests/selenium-grid.log
            ${{ github.workspace }}/sample-tests/target
            ${{ github.workspace }}/sample-tests/reports
            ${{ github.workspace }}/sample-java/screenshots
