name: Test boyka-framework release

on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: boyka-test-release-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    env:
      BS_USER: ${{ secrets.BS_USER }}
      BS_KEY: ${{ secrets.BS_KEY }}
      LT_USER: ${{ secrets.LT_USER }}
      LT_KEY: ${{ secrets.LT_KEY }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: mvn clean install -f core-java/pom.xml -DskipTests -Dcheckstyle.skip

      - name: Get the version
        id: version
        run: |
          export MVN_VERSION=$(node -pe "require('./website/package.json').version")
          echo "version=$MVN_VERSION" >> $GITHUB_OUTPUT

      - name: Start Selenium Grid
        if: inputs.run-grid
        run: |
          docker-compose -f core-java/compose/docker-compose.yml up

      - name: All Test execution
        run: mvn clean test -f sample-tests/pom.xml -Dboyka.version=${{ steps.version.outputs.version }}

      - name: Stop Selenium Grid
        if: inputs.run-grid && always()
        run: |
          docker-compose -f core-java/compose/docker-compose.yml down

      - name: Upload target folder
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: target
          retention-days: 1
          path: |
            ${{ github.workspace }}/sample-tests/logs
            ${{ github.workspace }}/sample-tests/selenium-grid.log
            ${{ github.workspace }}/sample-tests/target
            ${{ github.workspace }}/sample-java/screenshots
